"""removido campo de att_url

Revision ID: 44ec55ab330a
Revises: 458d70ba8cd4
Create Date: 2026-05-13 10:52:27.123127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ec55ab330a'
down_revision: Union[str, Sequence[str], None] = '458d70ba8cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mural_item', 'attachment_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item', sa.Column('attachment_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
