"""Alterando nome da coluna de relação com auth_user 2

Revision ID: aadfbc82a04a
Revises: 3a84d7748898
Create Date: 2026-04-27 16:02:39.923790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aadfbc82a04a'
down_revision: Union[str, Sequence[str], None] = '3a84d7748898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.alter_column('mural_item', 'starts_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('mural_item', 'ends_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('mural_item_created_by_fkey'), 'mural_item', type_='foreignkey')
    op.create_foreign_key(None, 'mural_item', 'auth_user', ['created_by_id'], ['id'])
    op.drop_column('mural_item', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mural_item', type_='foreignkey')
    op.create_foreign_key(op.f('mural_item_created_by_fkey'), 'mural_item', 'auth_user', ['created_by'], ['id'])
    op.alter_column('mural_item', 'ends_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('mural_item', 'starts_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('mural_item', 'created_by_id')
    # ### end Alembic commands ###
