"""removida colunda is_read

Revision ID: b51f2d8d2a94
Revises: aadfbc82a04a
Create Date: 2026-04-28 11:23:53.500529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51f2d8d2a94'
down_revision: Union[str, Sequence[str], None] = 'aadfbc82a04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mural_item_read', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item_read', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
