"""criando models iniciais

Revision ID: 14614379260c
Revises: 468193298ad0
Create Date: 2026-04-27 13:17:14.364931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14614379260c'
down_revision: Union[str, Sequence[str], None] = '468193298ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mural_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('summary', sa.String(length=500), nullable=True),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('item_type', sa.String(
                        length=30), nullable=False),
                    sa.Column('severity', sa.String(
                        length=20), nullable=False),
                    sa.Column('target_type', sa.String(
                        length=20), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_pinned', sa.Boolean(), nullable=False),
                    sa.Column('starts_at', sa.DateTime(), nullable=False),
                    sa.Column('ends_at', sa.DateTime(), nullable=True),
                    sa.Column('is_indefinite', sa.Boolean(), nullable=False),
                    sa.Column('until_read', sa.Boolean(), nullable=False),
                    sa.Column('external_link', sa.String(
                        length=500), nullable=True),
                    sa.Column('attachment_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('image_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('created_by', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['auth_user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_mural_item_id'),
                    'mural_item', ['id'], unique=False)
    op.create_table('mural_item_read',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mural_item_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=False),
                    sa.Column('read_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['mural_item_id'], ['mural_item.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('mural_item_id', 'user_id',
                                        name='uq_mural_item_read_user')
                    )
    op.create_index(op.f('ix_mural_item_read_id'),
                    'mural_item_read', ['id'], unique=False)
    op.create_table('mural_item_user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mural_item_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['mural_item_id'], ['mural_item.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_mural_item_user_id'),
                    'mural_item_user', ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_mural_item_user_id'), table_name='mural_item_user')
    op.drop_table('mural_item_user')
    op.drop_index(op.f('ix_mural_item_read_id'), table_name='mural_item_read')
    op.drop_table('mural_item_read')
    op.drop_index(op.f('ix_mural_item_id'), table_name='mural_item')
    op.drop_table('mural_item')
