"""Alterando nome da coluna de relação com auth_user

Revision ID: 360ba0682e81
Revises: 681d3aca61a8
Create Date: 2026-04-27 15:56:53.363302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '360ba0682e81'
down_revision: Union[str, Sequence[str], None] = '681d3aca61a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('mural_item', 'starts_at',
                    existing_type=postgresql.TIMESTAMP(),
                    server_default=sa.text('now()'),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False)
    op.alter_column('mural_item', 'ends_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mural_item', 'ends_at',
                    existing_type=sa.DateTime(timezone=True),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=True)
    op.alter_column('mural_item', 'starts_at',
                    existing_type=sa.DateTime(timezone=True),
                    server_default=None,
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False)
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'razao_social', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'numero', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'telefone1', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'codigo_ibge', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'telefone2', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'logradouro', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'complemento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'sales_channel', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'email', sa.VARCHAR(length=254), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'cod_center', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'UF', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'deposito', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'inscricao_estadual', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'cnpj', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'responsavel', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logistica_groupaditionalinformation', sa.Column(
        'CEP', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('logistica_groupaditi_group_id_355fe1f1_fk_auth_grou'), 'logistica_groupaditionalinformation', 'auth_group', [
                          'group_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_id'),
                  table_name='logistica_groupaditionalinformation')
    op.drop_index(op.f('ix_logistica_groupaditionalinformation_cod_iata'),
                  table_name='logistica_groupaditionalinformation')
    op.create_index(op.f('logistica_groupaditionalinformation_group_id_355fe1f1'),
                    'logistica_groupaditionalinformation', ['group_id'], unique=False)
    op.alter_column('logistica_groupaditionalinformation', 'id',
                    existing_type=sa.Integer(),
                    server_default=sa.Identity(
                        always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1),
                    type_=sa.BIGINT(),
                    existing_nullable=False,
                    autoincrement=True)
    op.add_column('auth_user', sa.Column('email', sa.VARCHAR(
        length=254), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('date_joined', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('last_name', sa.VARCHAR(
        length=150), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column(
        'is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('first_name', sa.VARCHAR(
        length=150), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('last_login', postgresql.TIMESTAMP(
        timezone=True), autoincrement=False, nullable=True))
    op.add_column('auth_user', sa.Column('password', sa.VARCHAR(
        length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.create_unique_constraint(
        op.f('auth_user_username_key'), 'auth_user', ['username'])
    op.create_index(op.f('auth_user_username_6821ab7c_like'),
                    'auth_user', ['username'], unique=False)
    op.alter_column('auth_user', 'id',
                    existing_type=sa.INTEGER(),
                    server_default=sa.Identity(
                        always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
                    existing_nullable=False,
                    autoincrement=True)
    # ### end Alembic commands ###
