"""adicionado campo Json para salvar anexos

Revision ID: 39cf219ab25a
Revises: 96209eb7d92c
Create Date: 2026-05-13 10:09:07.296951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39cf219ab25a'
down_revision: Union[str, Sequence[str], None] = '96209eb7d92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('mural_item_read', 'read_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mural_item_read', 'read_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=None,
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('mural_item', 'attachments')
    # ### end Alembic commands ###
