"""Alterando nome da coluna de relação com auth_user 2

Revision ID: 6288c3a68e83
Revises: 360ba0682e81
Create Date: 2026-04-27 15:58:42.441308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6288c3a68e83'
down_revision: Union[str, Sequence[str], None] = '360ba0682e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('mural_item_created_by_fkey'), 'mural_item', type_='foreignkey')
    op.create_foreign_key(None, 'mural_item', 'auth_user', ['created_by_id'], ['id'])
    op.drop_column('mural_item', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'mural_item', type_='foreignkey')
    op.create_foreign_key(op.f('mural_item_created_by_fkey'), 'mural_item', 'auth_user', ['created_by'], ['id'])
    op.drop_column('mural_item', 'created_by_id')
    # ### end Alembic commands ###
