"""Ajustadas referências de PK

Revision ID: 681d3aca61a8
Revises: 2cf650ef6d99
Create Date: 2026-04-27 15:25:47.474454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '681d3aca61a8'
down_revision: Union[str, Sequence[str], None] = '2cf650ef6d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mural_item_gai',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mural_item_id', sa.Integer(), nullable=False),
                    sa.Column('gai_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['gai_id'], ['logistica_groupaditionalinformation.id'], ),
                    sa.ForeignKeyConstraint(
                        ['mural_item_id'], ['mural_item.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_mural_item_gai_gai_id'),
                    'mural_item_gai', ['gai_id'], unique=False)
    op.create_index(op.f('ix_mural_item_gai_id'),
                    'mural_item_gai', ['id'], unique=False)
    op.create_table('mural_item_group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('mural_item_id', sa.Integer(), nullable=False),
                    sa.Column('group_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
                    sa.ForeignKeyConstraint(
                        ['mural_item_id'], ['mural_item.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_mural_item_group_id'),
                    'mural_item_group', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mural_item_group_id'),
                  table_name='mural_item_group')
    op.drop_table('mural_item_group')
    op.drop_index(op.f('ix_mural_item_gai_id'), table_name='mural_item_gai')
    op.drop_index(op.f('ix_mural_item_gai_gai_id'),
                  table_name='mural_item_gai')
    op.drop_table('mural_item_gai')
    # ### end Alembic commands ###
