"""removida colunda is_read

Revision ID: 96209eb7d92c
Revises: 6288c3a68e83
Create Date: 2026-04-28 11:23:27.522757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96209eb7d92c'
down_revision: Union[str, Sequence[str], None] = '6288c3a68e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mural_item_read', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mural_item_read', sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
